- customVariables: []
  description: Embedded library - Spring Cloud Config
  labels:
  - konveyor.io/include=always
  links: []
  message: The application embeds Spring Cloud Config.
  ruleID: configuration-management-0100
  tag:
  - Spring Cloud Config
  when:
    or:
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-config-client
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-starter-config
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-config-client
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-config-server
    - java.referenced:
        location: IMPORT
        pattern: org.springframework.cloud.config.server.EnableConfigServer.EnableConfigServer
    - builtin.filecontent:
        filePattern: (/|\\)(application|bootstrap)(-[a-zA-Z0-9]+)*?\.(properties|yaml|yml)$
        pattern: spring\.config\.import|spring\.cloud\.config\.uri
- customVariables: []
  description: Application properties file detected
  labels:
  - konveyor.io/include=always
  links: []
  message: Application properties file detected
  ruleID: configuration-management-0200
  tag:
  - Application Properties File
  - Application properties file detected
  when:
    builtin.file:
      pattern: ^application(-[a-zA-Z0-9]+)*?\.(properties|yml|yaml)$
- customVariables: []
  description: Spring datasource properties detected
  labels:
  - konveyor.io/include=always
  links: []
  message: Spring datasource properties detected
  ruleID: configuration-management-0300
  tag:
  - Spring Properties
  - Spring datasource properties detected
  when:
    builtin.filecontent:
      filePattern: (/|\\)application(-[a-zA-Z0-9]+)*?\.(properties|yml|yaml)$
      pattern: spring.datasource
- customVariables: []
  description: Spring logging properties detected
  labels:
  - konveyor.io/include=always
  links: []
  message: Spring logging properties detected
  ruleID: configuration-management-0400
  tag:
  - Spring Properties
  - Spring logging properties detected
  when:
    builtin.filecontent:
      filePattern: (/|\\)application(-[a-zA-Z0-9]+)*?\.(properties|yml|yaml)$
      pattern: logging.level.org.springframework
- customVariables: []
  description: Spring configuration properties annotation detected
  labels:
  - konveyor.io/include=always
  links: []
  message: Spring configuration properties annotation detected
  ruleID: configuration-management-0500
  tag:
  - Spring Properties
  - Spring configuration properties annotation detected
  when:
    java.referenced:
      location: ANNOTATION
      pattern: org.springframework.boot.context.properties.ConfigurationProperties
- customVariables: []
  description: Embedded library - Spring Cloud Vault
  labels:
  - konveyor.io/include=always
  links: []
  message: The application embeds Spring Cloud Vault.
  ruleID: configuration-management-0600
  tag:
  - Spring Cloud Vault
  when:
    or:
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-starter-vault-config
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-vault-config
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-vault-config
    - builtin.filecontent:
        filePattern: (/|\\)([a-zA-Z0-9._-]+)\.{extensions}$
        pattern: spring.cloud.vault
    - builtin.file:
        pattern: ^([a-zA-Z0-9._-]*)spring-cloud-vault([a-zA-Z0-9._-]*)\.jar$
