- category: potential
  customVariables: []
  description: Explicit Config Server connection info found in configuration file
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - domain=azure-readiness
  - category=spring-migration
  - Spring Cloud Config
  links:
  - title: Migrate Spring Boot applications to Azure Container Apps - Remove restricted configurations
    url: https://learn.microsoft.com/azure/developer/java/migration/migrate-spring-cloud-to-azure-container-apps#remove-restricted-configurations
  - title: Connect to a managed Config Server for Spring in Azure Container Apps
    url: https://learn.microsoft.com/azure/container-apps/java-config-server?tabs=azure-cli
  message: |-
    The application uses a Spring Cloud Config Server connection string.

     If you are migrating to Azure Container Apps, the connection info of Config Server can be injected automatically upon app start.
     Find any explicit configurations of config server connection info:

     If configured in **configuration files**: they will be ignored and overrided by Azure Container Apps.

     If configured in **command line parameters**, **Java system attribute**, **environment variable**: they need to be removed or you might experience conflicts and unexpected behavior.

     Configure the managed Config Server after creating an Azure Container Apps environment.
  ruleID: spring-boot-to-azure-config-server-01000
  tag:
  - Spring Cloud Config
  when:
    builtin.filecontent:
      filePattern: (/|\\)(application|bootstrap)(-[a-zA-Z0-9]+)*?\.(properties|yaml|yml)$
      pattern: spring\.config\.import|spring\.cloud\.config\.uri
- category: potential
  customVariables: []
  description: Spring Cloud Config Server found
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - domain=azure-readiness
  - category=spring-migration
  - Spring Cloud Config
  links:
  - title: Connect to a managed Config Server for Spring in Azure Container Apps
    url: https://learn.microsoft.com/azure/container-apps/java-config-server?tabs=azure-cli
  message: |-
    The application uses Spring Cloud Config Server.

     If you are migrating to Azure Container Apps, you can just configure the managed Config Server after creating an Azure Container Apps environment
  ruleID: spring-boot-to-azure-config-server-02000
  tag:
  - Spring Cloud Config
  when:
    or:
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-config-server
    - java.referenced:
        location: IMPORT
        pattern: org.springframework.cloud.config.server.EnableConfigServer.EnableConfigServer
